"""Add database indexes and initial migration

Revision ID: c9637b9bb437
Revises: 
Create Date: 2026-08-19 01:52:44.632725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9637b9bb437'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingestion_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pages_attempted', sa.Integer(), nullable=False),
    sa.Column('pages_succeeded', sa.Integer(), nullable=False),
    sa.Column('pages_failed', sa.Integer(), nullable=False),
    sa.Column('jobs_fetched', sa.Integer(), nullable=False),
    sa.Column('jobs_valid', sa.Integer(), nullable=False),
    sa.Column('jobs_invalid', sa.Integer(), nullable=False),
    sa.Column('jobs_new', sa.Integer(), nullable=False),
    sa.Column('jobs_duplicate', sa.Integer(), nullable=False),
    sa.Column('jobs_changed', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_runs_source'), 'ingestion_runs', ['source'], unique=False)
    op.create_index(op.f('ix_ingestion_runs_started_at'), 'ingestion_runs', ['started_at'], unique=False)
    op.create_index(op.f('ix_ingestion_runs_status'), 'ingestion_runs', ['status'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('external_id', sa.String(length=500), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('company', sa.String(length=300), nullable=False),
    sa.Column('company_slug', sa.String(length=300), nullable=True),
    sa.Column('company_logo', sa.String(length=1000), nullable=True),
    sa.Column('employment_type', sa.String(length=100), nullable=True),
    sa.Column('minimum_salary', sa.Float(), nullable=True),
    sa.Column('maximum_salary', sa.Float(), nullable=True),
    sa.Column('salary_period', sa.String(length=50), nullable=True),
    sa.Column('currency', sa.String(length=20), nullable=True),
    sa.Column('seniority', sa.JSON(), nullable=False),
    sa.Column('location_restrictions', sa.JSON(), nullable=False),
    sa.Column('timezone_restrictions', sa.JSON(), nullable=False),
    sa.Column('categories', sa.JSON(), nullable=False),
    sa.Column('parent_categories', sa.JSON(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('application_url', sa.String(length=1000), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_id', name='uq_jobs_source_external_id')
    )
    op.create_index(op.f('ix_jobs_company'), 'jobs', ['company'], unique=False)
    op.create_index(op.f('ix_jobs_created_at'), 'jobs', ['created_at'], unique=False)
    op.create_index(op.f('ix_jobs_employment_type'), 'jobs', ['employment_type'], unique=False)
    op.create_index(op.f('ix_jobs_maximum_salary'), 'jobs', ['maximum_salary'], unique=False)
    op.create_index(op.f('ix_jobs_minimum_salary'), 'jobs', ['minimum_salary'], unique=False)
    op.create_index(op.f('ix_jobs_published_at'), 'jobs', ['published_at'], unique=False)
    op.create_table('ingestion_errors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ingestion_run_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('offset', sa.Integer(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('error_type', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['ingestion_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_errors_ingestion_run_id'), 'ingestion_errors', ['ingestion_run_id'], unique=False)
    op.create_index(op.f('ix_ingestion_errors_source'), 'ingestion_errors', ['source'], unique=False)
    op.create_table('job_changes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('external_id', sa.String(length=500), nullable=False),
    sa.Column('old_content_hash', sa.String(length=64), nullable=False),
    sa.Column('new_content_hash', sa.String(length=64), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_changes_external_id'), 'job_changes', ['external_id'], unique=False)
    op.create_index(op.f('ix_job_changes_job_id'), 'job_changes', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_changes_source'), 'job_changes', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_changes_source'), table_name='job_changes')
    op.drop_index(op.f('ix_job_changes_job_id'), table_name='job_changes')
    op.drop_index(op.f('ix_job_changes_external_id'), table_name='job_changes')
    op.drop_table('job_changes')
    op.drop_index(op.f('ix_ingestion_errors_source'), table_name='ingestion_errors')
    op.drop_index(op.f('ix_ingestion_errors_ingestion_run_id'), table_name='ingestion_errors')
    op.drop_table('ingestion_errors')
    op.drop_index(op.f('ix_jobs_published_at'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_minimum_salary'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_maximum_salary'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_employment_type'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_created_at'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_company'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_ingestion_runs_status'), table_name='ingestion_runs')
    op.drop_index(op.f('ix_ingestion_runs_started_at'), table_name='ingestion_runs')
    op.drop_index(op.f('ix_ingestion_runs_source'), table_name='ingestion_runs')
    op.drop_table('ingestion_runs')
    # ### end Alembic commands ###
